---
title: "AC Transit Line 7 Stops and Political Boundaries"
author: "Charley Cowens"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
params:
  RefreshData: FALSE
---

```{r setup, include=FALSE}
if(!require(knitr)) {install.packages("knitr"); library(knitr)}
if(!require(dplyr)) {install.packages("dplyr"); library(dplyr)}
if(!require(readxl)) {install.packages("readxl"); library(readxl)}
if(!require(stringr)) {install.packages("stringr"); library(stringr)}
if(!require(sf)) {install.packages("sf"); library(sf)}
if(!require(mapview)) {install.packages("mapview"); library(mapview)}
if(!require(scales)) {install.packages("scales"); library(scales)}
if(!require(kableExtra)) {install.packages("kableExtra"); library(kableExtra)}
if(!require(ggplot2)) {install.packages("ggplot2"); library(ggplot2)}

opts_chunk$set(echo = FALSE)
```

```{r efresh}
if(params$RefreshData) source("get_stops.R")
```


```{r input}
StopsData <- readRDS("StopsData.rds")
Cities <- read_xlsx("ACTransitNorthWardsCities.xlsx")
Reps <- read_xlsx("ACTransitNorthWardsReps.xlsx")
```

# Contact Info for Line 7 ACTransit Directors

Their AC Transit web pages have their emails and phone numbers.

```{r contact}
kable(Reps)
```

# Directors by City

I count named unincorporated areas as cities.

```{r cities}
Cities %>% arrange(City) %>% kable()
```

# Number of Stops by City

The total number of stops is **`r nrow(StopsData)`**.

```{r by city}
StopsByCity <- StopsData %>% 
  group_by(City) %>% 
  summarize(Stops = n()) %>% 
  arrange(desc(Stops)) %>%
  mutate(Percentage = Stops / sum(Stops))

StopsByCity %>% 
  mutate(Percent = label_percent()(Percentage)) %>% 
  select(-Percentage) %>% 
  kable() %>% 
  kableExtra::kable_styling(full_width=FALSE, position="left")

```

```{r plot cities}
StopsByCity$ymax <- cumsum(StopsByCity$Percentage) 
StopsByCity$ymin <- c(0, head(StopsByCity$ymax, n=-1)) 
StopsByCity$labelPosition <- (StopsByCity$ymax + StopsByCity$ymin) / 2 
# Create the donut chart 
donut_chart <- ggplot(StopsByCity, aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=City)) + geom_rect() + coord_polar(theta="y") + 
# Transforms to circular coordinates 
xlim(c(2, 4)) + 
# Adjust x limits to create the hole
theme_void() +
# Remove unnecessary plot elements 
geom_text(aes(x=3.5, y=labelPosition, label=paste0(round(Percentage*100, 1), "%")), color = "black", size=4) + scale_fill_brewer(palette="Dark2") 
#Choose color palette, you can change this. # Print the donut chart 
print(donut_chart) 
```


# Full List of Stops

Sorted by geo coordinate latitude from north to south.

```{r stops data list, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
StopsData %>% 
  arrange(desc(Latitude)) %>% 
  mutate(Stop = paste0(`Stop Number`, " - ", `Stop Name`),
         Direction = str_sub(Direction, 1, 1)) %>% 
  select(Stop, Direction, City) %>% 
  left_join(Cities) %>% 
  kable()
```

## A Simple Map of Stops

```{r mapview data list, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
StopsData %>%
  left_join(Cities) %>% 
  st_as_sf(
    coords = c("Longitude", "Latitude"),
    crs    = 4326
  ) %>% mapview(legend=FALSE)
```



